- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceActor.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/condition/.gitignore
- flower.sample/src/main/java/com/ly/train/flower/common/sample/condition/ServiceA.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/condition/ServiceB.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/condition/ServiceC.java
条件分叉的时候，可以指定多个后续服务，服务之间用","分割。
`mx.setCondition("serviceE,serviceD");`
> support string array in condition fork

- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceFacade.java
new出来的ServiceRouter按flowName + serviceName保存到map中, 防止多次new ServiceRouter
> 保存ServiceRouter

- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceFacade.java
- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceRouter.java
> 修改同步调用ServiceContext为空的问题

- flower.common/src/main/java/com/ly/train/flower/common/service/web/Web.java
增加Web对象getJsonString方法，以捕获post提交的json串
> 增加Web对post提交的json数据提取

- flower.sample/pom.xml
- flower.sample/src/main/java/com/ly/train/flower/common/sample/web/dao/GoodsDao.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/web/dao/OrderDao.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/web/dao/UserDao.java
- flower.sample/src/main/resources/spring-mybatis.xml
add dependency : spring-jdbc and spring-tx
> add dependency : spring-jdbc and spring-tx

- flower-bom/pom.xml
- flower.assembly/pom.xml
- flower.center/pom.xml
- flower.common/pom.xml
- flower.common/src/test/java/com/ly/train/flower/base/TestBase.java
- flower.common/src/test/java/com/ly/train/flower/common/actor/ServiceRouterTest.java
- flower.sample/pom.xml
- flower.web/pom.xml
- pom.xml
update flower version from 0.1.1 to 0.1.2
> update flower version from 0.1.1 to 0.1.2

- flower.bom/pom.xml
- flower.sample/src/main/java/com/ly/train/flower/common/sample/condition/Sample.java
- flower.sample/src/main/resources/sample.services
- flower.sample/src/main/resources/supervisor.services
- pom.xml
rename flower-bom to flower.bom
> rename flower-bom to flower.bom

- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceFacade.java
- flower.web/src/main/java/com/ly/flower/web/spring/FlowerController.java
- pom.xml
修复doc@see，修复pom中对flower.bom的依赖
> 修复doc@see，修复pom中对flower.bom的依赖

- .gitignore
- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceActorFactory.java
- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceFacade.java
- flower.common/src/main/java/com/ly/train/flower/common/actor/ServiceRouter.java
- flower.common/src/main/java/com/ly/train/flower/common/actor/SupervisorActor.java
- flower.common/src/main/java/com/ly/train/flower/common/util/Constant.java
- flower.common/src/main/resources/application.conf
> 守护actor-SupervisorActor，对子actor负责

- flower.sample/src/main/java/com/ly/train/flower/common/sample/aggregate/controller/AggregateController.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/aggregate/service/ServiceReceiveA.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/aggregate/service/ServiceReceiveAB.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/supervisor/service/Service4.java
- flower.sample/src/main/java/com/ly/train/flower/common/sample/textflow/service/Service4.java
示例兼容AggregateService返回List<Object> 结果集
>  示例兼容AggregateService返回List<Object> 结果集，

- flower.assembly/pom.xml
- sbin/daemon.sh
- sbin/start-center.sh
- sbin/start-container.sh
- sbin/stop-center.sh
- sbin/stop-container.sh
增加启动flower.center， flower.container的脚本
> add some script

- flower.common/src/main/java/com/ly/train/flower/common/akka/FlowRouter.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceActorFactory.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceFacade.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/ServiceActor.java
- flower.common/src/test/java/com/ly/train/flower/registry/simple/SimpleRegistryTest.java
1. 修复FlowerController控制actor数量时导致了远程调用有问题，现在还原
2. 修改变量名称flowNumber为actorNumber
> 修改变量名称flowNumber为actorNumber

- flower.common/src/main/java/com/ly/train/flower/common/akka/FlowRouter.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceActorFactory.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceRouter.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/ServiceActor.java
- flower.common/src/main/java/com/ly/train/flower/common/service/impl/AggregateService.java
- flower.common/src/test/java/com/ly/train/flower/common/akka/actor/ServiceFacadeTest.java
1. BUGFIX：多线程环境下聚合服务结果错乱
2. FlowNumber和ActorNumber概念区分开
>  BUGFIX：多线程环境下聚合服务结果错乱，避免使用锁

- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceActorFactory.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/ServiceRouter.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/ServiceActor.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/SupervisorActor.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/command/Command.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/command/CommandType.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/command/CreateCommand.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/command/GetContextCommand.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/command/Type.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/message/Message.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/wrapper/ActorRefWrapper.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/wrapper/ActorSelectionWrapper.java
- flower.common/src/main/java/com/ly/train/flower/common/akka/actor/wrapper/ActorWrapper.java
- flower.common/src/main/java/com/ly/train/flower/common/service/container/ServiceContext.java
- flower.common/src/main/java/com/ly/train/flower/common/service/message/FirstMessage.java
- flower.common/src/main/java/com/ly/train/flower/common/service/message/FlowMessage.java
- flower.common/src/main/java/com/ly/train/flower/common/service/message/ReturnMessage.java
- flower.common/src/main/java/com/ly/train/flower/common/util/IdGenerator.java
- flower.common/src/main/java/com/ly/train/flower/common/util/OSInfoUtil.java
- flower.common/src/main/java/com/ly/train/flower/common/util/OSPlatform.java
- flower.common/src/main/java/com/ly/train/flower/config/FlowerConfig.java
- flower.common/src/main/java/com/ly/train/flower/registry/AbstractRegistry.java
- flower.common/src/main/java/com/ly/train/flower/registry/redis/RedisRegistry.java
- flower.common/src/main/resources/application.conf
- flower.common/src/test/java/com/ly/train/flower/common/akka/actor/ActorSelectionTest.java
- flower.common/src/test/resources/flower.yml
默认值parallelismMin: 8, parallelismMax: 256, parallelismFactor: 8
> flower.yml里可以自定义并行度

- flower.web/src/main/java/com/ly/train/flower/web/spring/FlowerController.java
rm IOException
- ......
- ......
- ......
> rm IOException

- pom.xml
（简明扼要描述一下PR做了什么？）
- ......
- ......
- ......
>  rm formatter

- flower.core/src/main/java/com/ly/train/flower/core/akka/FlowerActorSystem.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/ServiceActorFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/wrapper/ActorLocalWrapper.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/wrapper/ActorRemoteWrapper.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/router/ServiceRouter.java
- flower.tools/flower.tools.http/src/main/java/com/ly/train/flower/tools/http/HttpFactory.java
- flower.tools/flower.tools.http/src/main/java/com/ly/train/flower/tools/http/factory/httpasyncclient/HttpAsyncClientFactory.java
- flower.tools/flower.tools.http/src/main/java/com/ly/train/flower/tools/http/factory/httpasyncclient/HttpClientCallback.java
- flower.tools/flower.tools.http/src/main/java/com/ly/train/flower/tools/http/factory/okhttp/OKHttpFactory.java
- flower.tools/flower.tools.http/src/main/java/com/ly/train/flower/tools/http/util/NamedThreadFactory.java
- flower.tools/flower.tools.http/src/test/java/com/ly/train/flower/tools/http/factory/httpasyncclient/HttpAsyncClientFactoryTest.java
- flower.tools/flower.tools.http/src/test/java/com/ly/train/flower/tools/http/factory/okhttp/TestHttp.java
- flower.tools/flower.tools.http/src/test/java/com/ly/train/flower/tools/http/factory/okhttp/TestHttp2.java
- flower.tools/flower.tools.http/src/test/java/com/ly/train/flower/tools/http/factory/okhttp/TestHttpClient.java
change name HttpClient to HttpAsyncClient
- change name HttpClient to HttpAsyncClient
- akka remote actor 
- ......
> change name HttpClient to HttpAsyncClient

- flower.center/flower.center.core/src/main/java/com/ly/train/flower/center/core/service/ServiceInfoRegisterService.java
- flower.common/src/main/java/com/ly/train/flower/common/util/Constant.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/FlowerActorSystem.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/ServiceActorFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/AbstractFlowerActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/ServiceActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/SupervisorActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/wrapper/ActorLocalWrapper.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/wrapper/ActorRemoteRouterWrapper.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/wrapper/ActorRemoteWrapper.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/router/FlowRouter.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/router/ServiceRouter.java
- flower.core/src/main/java/com/ly/train/flower/core/loadbalance/RoundLoadBalance.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/ServiceFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/ServiceFlow.java
- flower.core/src/main/java/com/ly/train/flower/registry/simple/SimpleRegistry.java
- flower.core/src/main/resources/application.conf
- flower.core/src/test/java/com/ly/train/flower/core/akka/actor/ActorSelectionTest.java
- flower.core/src/test/java/com/ly/train/flower/registry/simple/SimpleRegistryTest.java
- flower.registry/flower.registry.api/src/main/java/com/ly/train/flower/registry/AbstractRegistry.java
- flower.web/src/test/resources/application.yml
flower core actor 更新
FlowerActorSystem承载了Akka交互的功能
ServiceActorFactory负责管理actor
> flower core actor 更新

- flower.common/pom.xml
- flower.common/src/main/java/com/ly/train/flower/common/util/FlowerVersion.java
- flower.common/src/main/resources/FlowerVersion.properties
- flower.common/src/test/java/com/ly/train/flower/common/util/FlowerVersionTest.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/simple/SimpleFlowerFactory.java
- pom.xml
1. add FlowerVersion and log flower environment
2. update fastjson version to 1.2.58
> add FlowerVersion and log flower environment

- .travis.yml
- flower.boot.starter/pom.xml
- flower.common/src/main/java/com/ly/train/flower/common/core/Ordered.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/ServiceActor.java
- flower.web/src/main/java/com/ly/train/flower/web/spring/FlowerController.java
- pom.xml
add module flower.boot.starter
- add module flower.boot.starter
> add module flower.boot.starter

- flower.bom/pom.xml
- flower.boot.starter/pom.xml
- flower.center/flower.center.api/pom.xml
- flower.center/flower.center.core/pom.xml
- flower.center/flower.center.impl/pom.xml
- flower.center/pom.xml
- flower.common/pom.xml
- flower.config/pom.xml
- flower.container/pom.xml
- flower.core/pom.xml
- flower.filter/flower.filter.api/pom.xml
- flower.filter/flower.filter.opentracing/pom.xml
- flower.filter/pom.xml
- flower.registry/flower.registry.api/pom.xml
- flower.registry/flower.registry.zookeeper/pom.xml
- flower.registry/pom.xml
- flower.sample/pom.xml
- flower.serializer/flower.serializer.api/pom.xml
- flower.serializer/flower.serializer.hessian/pom.xml
- flower.serializer/pom.xml
- flower.test/pom.xml
- flower.tools/flower.tools.http/pom.xml
- flower.tools/pom.xml
- flower.web/pom.xml
- pom.xml
> update version to 1.0.1

- flower.common/src/main/java/com/ly/train/flower/common/core/service/ServiceContext.java
- flower.common/src/main/java/com/ly/train/flower/common/exception/FlowException.java
- flower.common/src/main/java/com/ly/train/flower/common/exception/FlowNotFoundException.java
- flower.common/src/main/java/com/ly/train/flower/common/exception/FlowerException.java
- flower.common/src/main/java/com/ly/train/flower/common/exception/ServiceException.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/AbstractFlowerActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/mailbox/FlowerMessageQueueSemantics.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/mailbox/bounded/FlowerBoundedMailbox.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/mailbox/bounded/FlowerBoundedMessageQueue.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/mailbox/unbounded/FlowerUnboundedMailbox.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/mailbox/unbounded/FlowerUnboundedMessageQueue.java
- flower.core/src/main/resources/application.conf
- flower.core/src/main/resources/flower.conf
- flower.core/src/test/java/com/ly/train/flower/core/akka/router/ServiceRouterTest.java
- BUGFIX: when the attachments is null, there is no need to create a new ConcurrentHashMap of ServiceContext
- add flower mailbox, both boundedmailbox and unboundedmailbox
> add flower mailbox

- flower.bom/pom.xml
- flower.config/src/main/java/com/ly/train/flower/config/FlowerConfig.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/ActorFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/BlockedThreadChecker.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/FlowerActorSystem.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/ServiceActorFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/AbstractFlowerActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/ServiceActor.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/SupervisorActor.java
add BlockedThreadChecker
blockedThreadCheckInterval: 1000
warningExceptionTime: 5000
Fixes #119 阻塞检测
> add BlockedThreadChecker

- flower.ddd/pom.xml
- flower.ddd/src/main/java/com/ly/train/flower/ddd/autoconfigure/DDDBeanPostProssor.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/gateway/impl/DefaultCommandGateway.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/gateway/impl/DefaultQueryGateway.java
- flower.ddd/src/test/java/com/ly/train/flower/ddd/command/FoodCart.java
BUGFIX: 未开启事务时，TransactionTemplate类找不到。
> bugfix: TransactionTemplate not found

- flower.common/src/main/java/com/ly/train/flower/common/core/web/Web.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/annotation/QueryHandler.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/autoconfigure/DDDBeanPostProssor.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/autoconfigure/DDDBeanRegistryPostProcessor.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/config/DDDConfig.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/exception/QueryHandlerNotFoundException.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/gateway/impl/DefaultQueryGateway.java
- flower.ddd/src/main/java/com/ly/train/flower/ddd/service/QueryHandlerService.java
@QueryHandler handle QueryGateway
@CommandHandler handle CommandGateway
...
- ......
- ......
- ......
> split @QueryHandler from @CommandHandler

- flower.common/src/main/java/com/ly/train/flower/common/lifecyle/AbstractInit.java
- flower.common/src/main/java/com/ly/train/flower/common/lifecyle/AbstractLifecycle.java
- flower.common/src/main/java/com/ly/train/flower/common/lifecyle/IInit.java
- flower.common/src/main/java/com/ly/train/flower/common/lifecyle/Lifecycle.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/FlowerActorSystem.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/ServiceActorFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/ServiceFactory.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/simple/SimpleFlowerFactory.java
- flower.core/src/test/java/com/ly/train/flower/core/service/container/ServiceFactoryTest.java
lifecyle manage of flower
three step of flower life :
1. init
2. start
3. stop
> lifecyle manage of flower

- flower.core/src/main/java/com/ly/train/flower/core/akka/ServiceFacade.java
- flower.core/src/main/java/com/ly/train/flower/core/akka/actor/ServiceActor.java
- flower.core/src/main/java/com/ly/train/flower/core/service/container/ServiceFlow.java
- flower.core/src/test/java/com/ly/train/flower/core/akka/ServiceFacadeTest.java
#61 支持流程之外的服务调用
- 异步调用
```
@Test
public void testAsyncCall() {
serviceFacade.asyncCall("UserServiceA", new User());
}
```
- 同步调用
```
@Test
public void testSyncCall() {
serviceFacade.asyncCall("UserServiceA", new User());
}
```
> #61 支持流程之外的服务调用

- flower.bom/pom.xml
- flower.boot.starter/pom.xml
- flower.center/flower.center.api/pom.xml
- flower.center/flower.center.core/pom.xml
- flower.center/flower.center.impl/pom.xml
- flower.center/pom.xml
- flower.common/pom.xml
- flower.config/pom.xml
- flower.container/pom.xml
- flower.core/pom.xml
- flower.ddd/pom.xml
- flower.filter/flower.filter.api/pom.xml
- flower.filter/flower.filter.opentracing/pom.xml
- flower.filter/pom.xml
- flower.registry/flower.registry.api/pom.xml
- flower.registry/flower.registry.simple/pom.xml
- flower.registry/flower.registry.zookeeper/pom.xml
- flower.registry/pom.xml
- flower.sample/pom.xml
- flower.serializer/flower.serializer.api/pom.xml
- flower.serializer/flower.serializer.hessian/pom.xml
- flower.serializer/pom.xml
- flower.test/pom.xml
- flower.tools/flower.tools.http/pom.xml
- flower.tools/pom.xml
- flower.web/pom.xml
- pom.xml
> release 1.0.1.RELEASE

- flower.bom/pom.xml
- flower.boot.starter/pom.xml
- flower.center/flower.center.api/pom.xml
- flower.center/flower.center.core/pom.xml
- flower.center/flower.center.impl/pom.xml
- flower.center/pom.xml
- flower.common/pom.xml
- flower.config/pom.xml
- flower.container/pom.xml
- flower.core/pom.xml
- flower.ddd/pom.xml
- flower.filter/flower.filter.api/pom.xml
- flower.filter/flower.filter.opentracing/pom.xml
- flower.filter/pom.xml
- flower.registry/flower.registry.api/pom.xml
- flower.registry/flower.registry.simple/pom.xml
- flower.registry/flower.registry.zookeeper/pom.xml
- flower.registry/pom.xml
- flower.sample/pom.xml
- flower.serializer/flower.serializer.api/pom.xml
- flower.serializer/flower.serializer.hessian/pom.xml
- flower.serializer/pom.xml
- flower.test/pom.xml
- flower.tools/flower.tools.http/pom.xml
- flower.tools/pom.xml
- flower.web/pom.xml
- pom.xml
update flower version to 1.0.2
update akka version to 2.5.26
> update version to 1.0.2

- docs/_docsify/_shadow/CHANGELOG.md
- docs/_docsify/_shadow/CODE_OF_CONDUCT.md
- docs/_docsify/_shadow/CONTRIBUTING.md
- docs/_docsify/_sidebar.md
- docs/showcase.md
- docs/tools/README.md
- docs/tools/http.md
- add docs of flower.tools.http
- add docs of flower.showcase
> docs : update docs

- docs/_docsify/_navbar.md
- docs/_docsify/flower.js
- docs/_sidebar.md
- docs/en-us/README.md
- docs/en-us/_sidebar.md
- docs/index.html
update flower docs 
- flower docs 
- en-us language docs
> chore: update flower docs

- pom.xml
version: upgrade guava's version to 33.4.6-jre
- version: upgrade guava's version to 33.4.6-jre
> version: upgrade guava's version to 33.4.6-jre
